---
# handlers file for fips

- name: Get default kernel
  ansible.builtin.command:
    cmd: grubby --default-kernel
  register: fips_default_kernel

- name: Update default kernel arguments
  ansible.builtin.command:
    cmd: grubby --update-kernel=$(grubby --default-kernel) --args=fips=1
  notify:
    - Reboot

- name: Reboot
  ansible.builtin.reboot:
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
